version: '3'
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - jenkins-nexus

  nexus:
    image: sonatype/nexus3
    ports:
      - "81:8081"
    networks:
      - jenkins-nexus

networks:
  jenkins-nexus: {}