version: '3'
services:

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - jenkins-nexus

  nexus: #так как не знаю как не знаю как выполнять домашку по nexus, то соответственно этот пункт не сделан
         #но скорее всего нужен докер-образ с ansible и в докерфайле описать как используется роль из ДЗ по nexus   
    image: sonatype/nexus3
    ports:
      - "81:8081"
    networks:
      - jenkins-nexus

networks:
  jenkins-nexus: {}