apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
spec:
  rules:
    - host: {{ .Values.ingrees.hostname }}
      http:
        paths:
          - path: {{ .Values.ingrees.path }}
            pathType: {{ .Values.ingrees.pathType }}
            backend:
              service:
                name: {{ .Values.service.name }}-svc
                port:
                  number: {{ .Values.service.port }}