replicas: 1

service:
  name: wcg
  type: ClusterIP
  port: 80

container:
  label: word-cloud-generator
  APP_PORT: 8888
  name: word-cloud-generator

image:
  repo_owner: GITHUB_REPOSITORY_OWNER
  repository: wcg
  tag: 1.0.0

ingress:
  enabled: true
  hostname: Your_IP
  path: /
  pathType: Prefix