- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Creating the init.groovy.d directory
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory

- name: Copying scripts to the init.groovy.d directory
  synchronize:
    src: /home/vagrant/scripts/
    dest: /var/lib/jenkins/init.groovy.d/

- name: Setting the owner and group for the init.groovy.d directory
  replace:
    #state: directory
    #owner: jenkins
    path: /lib/systemd/system/jenkins.service
    regexp: '^Environment="JAVA_OPTS=-Djava.awt.headless=true"'
    replace: 'Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

- name: restart Jenkins
  service:
    name: jenkins
    state: restarted
#- name: Get Jenkins crumb
#  uri:
#    url: "http://localhost:8080/crumbIssuer/api/json"
#    method: POST
#    user: admin
#    password: admin
#    register: crumb_output

#- debug:
#    var: crumb_output.json.crumb

- name: Install plugins Jenkins
  jenkins_plugin:
    url: http://localhost
    state: present
    name:
      - locale:314.v22ce953dfe9e
      - configuration-as-code:1647.ve39ca_b_829b_42
      - golang:1.4

- name: Copying jenkins.uaml home directory
  copy:
    src: jenkins.yaml
    dest: /home/jenkins/jenkins.yaml

- name: Updating the service configuration
  systemd:
    daemon_reload: yes

- name: restart Jenkins
  service:
    name: jenkins
    state: restarted    