unclassified:
  locale:
    systemLocale: en
    ignoreAcceptLanguage: true

tool:
  go:
    installations:
    - name: "go_lang"
      properties:
      - installSource:
          installers:
          - golangInstaller:
              id: "1.16"