name: hometask
on:
  push:
    branches:
      - master
  workflow_dispatch:
env:
  TAG: ${{ github.sha }}
  REGISTRY: ghcr.io #(нужно уточнить)
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            Dockerfile.multi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${GITHUB_REPOSITORY_OWNER}
          password: ${{ secrets.ACTION_TOKEN }}  
      - name: Build Docker image
        run: |
          docker buildx build \
            --file Dockerfile.multi \
            --tag ghcr.io/${GITHUB_REPOSITORY_OWNER}/wcg:${{ env.TAG }} \
            --tag ghcr.io/${GITHUB_REPOSITORY_OWNER}/wcg:latest \
            --progress plain \
            .
      - name: Push Docker image to GitHub Registry
        run: |
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/wcg:${{ env.TAG }}
          docker push ghcr.io/${GITHUB_REPOSITORY_OWNER}/wcg:latest
